using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pipes : MonoBehaviour
{
    public float speed = 5f;
    private float leftEdge;

    private void Start()
    {
        // TODO: Replace with code below to just remove by the width
        //float width = GetComponent<SpriteRenderer>().bounds.size.x;
        //leftEdge = Camera.main.ScreenToWorldPoint(Vector3.zero).x - width;
        leftEdge = Camera.main.ScreenToWorldPoint(Vector3.zero).x - 1;
    }

    private void Update()
    {
        transform.position += Vector3.left * speed * Time.deltaTime;
        if (transform.position.x < leftEdge)
        {
            Destroy(gameObject);
        }
    }
}
